version: '3'
services:
  client:
    build: client
    ports:
      - '8080:8080'
  server:
    build: server
    environment:
      - PORT=5000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:8080
      - JWT_SECREET = hvdvay6ert72839289()aiyg8t87qt72393293883uhefiuh78ttq3ifi78272jbkj?[]]pou89ywe
      - MONGO_URI=mongodb://127.0.0.1:27017/Lava
    ports:
      - '5000:5000'
